// export const menuItems = [
//     { id: 'event1', title: 'Birthday Party' },
//     { id: 'event2', title: 'Wedding' },
//     { id: 'event3', title: 'Conference' },
//     { id: 'event4', title: 'Marthon' },
//     { id: 'event5', title: 'Christmas' },
//     { id: 'event6', title: 'New Year' },
//     { id: 'event7', title: 'Halloween' }
//   ];

export const menuItems = [
  { id: 'OwScAW3E', title: 'Hackathon: Building Apps for Social Good', status: 'past' },
  { id: 'QluqTgqU', title: 'Book Fair', status: 'past' },
  { id: '9vDDKICX', title: 'Art Exhibition', status: 'past' },
  { id: 'lgdOhHLZ', title: 'Music Festival: Sounds of Summer', status: 'past' },
  { id: 'XhHxsRPn', title: 'Annual Tech Conference', status: 'past' },
  { id: '4vzn6T41', title: 'Art Exhibition in London', status: 'upcoming' },
  { id: 'PwUs5bod', title: 'Marathon', status: 'past' },
  { id: 'KYRbQxOD', title: 'New Year Bash', status: 'past' },
  { id: 'WmdkDfiv', title: 'Cooking Class: Italian Cuisine Basics', status: 'past' },
  { id: 'KWdqMhhS', title: 'Outdoor Yoga Session', status: 'past' },
  { id: 'WoiUjPRm', title: 'Halloween Party: Haunted Night', status: 'past' },
  { id: 'qgRDoTNr', title: 'Christmas Market', status: 'past' },
  { id: 'w6TyoRpD', title: 'Line Dancing Workshop', status: 'past' },
  { id: 'Qdc7YoGp', title: 'Art Gallery Opening Night', status: 'upcoming' },
  { id: 'gm7qTwLG', title: 'Weekend Coding Bootcamp', status: 'past' },
  { id: 'IqXpWCHo', title: 'Valentine’s Day Dinner Cruise', status: 'past' },
  { id: 'AbOwIpgT', title: 'Photography Contest', status: 'past' },
  { id: 'RfIQlG6y', title: 'Backyard Barbecue', status: 'past' },
  { id: 'TmwBXPqR', title: 'Business Networking Brunch', status: 'past' },
  { id: 'OngMZX3L', title: 'Community Park Cleanup Drive', status: 'past' },
  { id: 'wTUHsC7Z', title: 'Easter Egg Hunt', status: 'past' },
  { id: 'XIoThGyF', title: 'Coding for Kids Workshop', status: 'past' },
  { id: 'RYNcGHqV', title: 'Open Mic Poetry Night', status: 'past' },
  { id: 'TZdoKYqH', title: 'Basketball Tournament Finals', status: 'past' },
  { id: 'WnUSvTLm', title: 'Learn to Line Dance', status: 'past' },
  { id: 'BpVXqlGt', title: 'Town Hall Meeting', status: 'upcoming' },
  { id: 'HKXwvOmP', title: 'Cooking Class: Vegan Delights', status: 'past' },
  { id: 'KYmlTXGz', title: 'Spring Flower Show', status: 'past' },
  { id: 'VNwpTXkM', title: 'Thanksgiving Feast', status: 'past' },
  { id: 'PQrVWzNY', title: 'Wine Tasting Evening', status: 'past' },
  { id: 'ZTXmGYKd', title: 'Karaoke Night', status: 'past' },
  { id: 'MKoGYXTq', title: 'Outdoor Cinema: Classic Films', status: 'past' },
  { id: 'RYXZWPkG', title: 'Charity Gala Dinner', status: 'past' },
  { id: 'GMZTXKWq', title: 'Science Fair', status: 'past' },
  { id: 'XTqRYpWM', title: 'Holiday Baking Workshop', status: 'past' },
  { id: 'ZWMoRYNT', title: 'Annual Garage Sale', status: 'past' },
  { id: 'NPTXWYKm', title: 'Parent-Child Soccer Match', status: 'past' },
  { id: 'TqXMWYKZ', title: 'Meditation Retreat Weekend', status: 'past' },
  { id: 'XpGTYKWM', title: 'Beach Cleanup Day', status: 'past' },
  { id: 'NZWMXTYP', title: 'Horseback Riding Adventure', status: 'past' },
  { id: 'KMRYpXTq', title: 'Chess Tournament', status: 'past' },
  { id: 'YXNTqWMZ', title: 'Comedy Club Night', status: 'past' },
  { id: 'NZXYKWMG', title: 'Local Farmers Market', status: 'past' },
  { id: 'XTMRYZPW', title: 'Live Jazz Concert', status: 'past' },
  { id: 'KYWMZTXP', title: 'Sunset Photography Workshop', status: 'past' },
  { id: 'GYXTqNMW', title: 'City Walking Tour', status: 'past' },
  { id: 'RYKMWZXT', title: 'Silent Disco Party', status: 'past' },
  { id: 'TqWMXYNZ', title: 'Wine and Cheese Night', status: 'past' },
  { id: 'GXTWMRYZ', title: 'Volunteering at Animal Shelter', status: 'past' },
  { id: 'MZKXTYPW', title: 'Rock Climbing Adventure', status: 'past' },
  { id: 'XTZKWMRY', title: 'Spoken Word Showcase', status: 'past' },
  { id: 'YWKMRYXT', title: 'Astronomy Night: Stargazing', status: 'past' },
  { id: 'ZTWMXYNK', title: 'Outdoor BBQ Picnic', status: 'past' },
  { id: 'TYZNWMXK', title: 'Murder Mystery Dinner Party', status: 'upcoming' },
  { id: 'MZYWXKNT', title: 'Charity Fun Run', status: 'past' },
  { id: 'XYNMZRTK', title: 'Winter Craft Fair', status: 'past' },
  { id: 'MRKWXTNZ', title: 'Board Game Night', status: 'past' },
  { id: 'ZNXRYMKW', title: 'Kids Coding Hackathon', status: 'upcoming' },
  { id: 'PWYMZKXT', title: 'City Food Truck Festival', status: 'past' },
  { id: 'TXYNZMWR', title: 'Family Movie Night', status: 'past' },
  { id: 'ZPWNXYKT', title: 'Local History Walking Tour', status: 'past' },
  { id: 'WMRYXTKN', title: 'Improv Theater Performance', status: 'past' },
  { id: 'NZXYTWMK', title: 'Virtual Reality Gaming Night', status: 'past' },
  { id: 'RMXTYKZW', title: 'Outdoor Adventure Fair', status: 'past' },
  { id: 'KMWXTZNY', title: 'Evening of Piano Classics', status: 'past' },
  { id: 'ZTXYWKRN', title: 'Community Sports Day', status: 'past' },
  { id: 'TMXWKYRN', title: 'Local Authors Book Launch', status: 'past' },
  { id: 'YTZNMWPK', title: 'Midnight Dance Party', status: 'past' },
  { id: 'MZNXKWYT', title: 'City Marathon Festival', status: 'past' },
  { id: 'RYKTXWMN', title: 'Pottery Workshop', status: 'upcoming' }
];
